---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: go-hello-http
spec:
  generators:
    - list:
        elements:
          - namespace: prod
          - namespace: stage
  goTemplate: true
  template:
    metadata:
      name: "{{ .namespace }}-go-hello-world"
    spec:
      project: default
      source:
        helm:
          valueFiles:
            - values.yaml
        path: go-hello-http
        repoURL: https://github.com/ironcore864/gitops-argocd
        targetRevision: HEAD
      destination:
        namespace: "{{ .namespace }}"
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
