---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tiexin-test
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ironcore864/go-hello-http:0.0.X
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/ironcoreworks/gitops
    targetRevision: main
    path: go-hello-http
  destination:
    server: https://kubernetes.default.svc
    namespace: tiexin-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
